name: Bryanna Millis Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21548
title: 'Art, poetry, and inspiration'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f5ecd9'
    - '#d5c4a7'
    - '#040000'
    - '#a67a6f'
    - '#5a594b'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
