name: Bryanna Millis Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.2021277
title: Bryanna Millis Art
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#faecdb'
    - '#48312b'
    - '#050402'
    - '#e4bea6'
    - '#b07568'
  brandStrength: 0.75
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
