layout_spectrum: 1
typography_spectrum: 0.2021277
color:
  lightness: 0.5765957
  brandStrength: 0.8369877
  saturation: 0.6191489
  rhythmicContrast: 1
  brandColors:
    - '#F2E1CF'
    - '#170D0D'
    - '#5C4A4B'
    - '#C7A399'
    - '#A37765'
name: Bryanna Millis Art
