name: Bryanna Millis Art
favicon: null
layout_spectrum: 1
typography_spectrum: 0.21548
title: The revolution begins
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f6e5c1'
    - '#211212'
    - '#c6796c'
    - '#a44f49'
    - '#563628'
  brandStrength: 1
  lightness: 0.625
  saturation: 0.625
  rhythmicContrast: 1
purpose: []
